/**
 * `kontext pack` — assemble a ranked, token-budgeted context bundle.
 *
 * The design rule here: **omission is never silent**. Anything that matched the
 * task but did not make it into the bundle is reported on stderr with a reason,
 * so the human (or agent) knows what they are missing rather than assuming the
 * bundle is complete.
 */

import type { ContextPack, DocKind } from '../types.js';
import { loadConfig, findRepoRoot } from '../core/config.js';
import { scanDocs } from '../core/scan.js';
import { assessAll } from '../core/freshness.js';
import { buildPack } from '../core/rank.js';
import { type CommandDef, type FlagSpecs, getBool, getList, getNumber, getString, parseArgs } from '../util/args.js';
import { SEP, c, err, errWrap, humanTokens, json, markGlyph, out, terminalWidth, truncatePath } from '../util/render.js';
import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, isAbsolute, resolve } from 'node:path';

const KINDS: DocKind[] = ['guide', 'decision', 'runbook', 'reference', 'handoff', 'index', 'spec'];

const flags: FlagSpecs = {
  budget: { type: 'number', placeholder: '<n>', description: 'Token ceiling for the bundle (default: config.defaultPackBudget).' },
  json: { type: 'boolean', description: 'Emit the raw ContextPack object instead of markdown.' },
  'include-stale': { type: 'boolean', description: 'Allow stale/expired docs into the bundle (they are excluded by default).' },
  kind: { type: 'list', placeholder: '<k>', description: 'Restrict to these doc kinds. Repeatable or comma-separated.' },
  out: { type: 'string', placeholder: '<file>', description: 'Write the bundle to a file instead of stdout.' },
};

/**
 * Shift a doc's ATX headings down two levels so the pack reads as one document
 * instead of a pile of competing H1s. Fenced code blocks are left alone.
 */
export function demoteHeadings(md: string, by = 2): string {
  const lines = md.split('\n');
  let fence: string | null = null;
  return lines
    .map((line) => {
      const f = /^\s*(```+|~~~+)/.exec(line);
      if (f && f[1]) {
        if (fence === null) fence = f[1][0] ?? '`';
        else if (f[1][0] === fence) fence = null;
        return line;
      }
      if (fence !== null) return line;
      const h = /^(#{1,6})(\s+.*)$/.exec(line);
      if (!h || !h[1] || !h[2]) return line;
      const level = Math.min(6, h[1].length + by);
      return `${'#'.repeat(level)}${h[2]}`;
    })
    .join('\n');
}

/** The markdown rendering of a pack: a provenance header, then one section per doc. */
export function renderPackMarkdown(pack: ContextPack): string {
  const lines: string[] = [];
  lines.push(`# Context pack: ${pack.task}`);
  lines.push('');
  lines.push(`> Generated by kontext at ${pack.generatedAt}.`);
  lines.push(
    `> ${pack.entries.length} document${pack.entries.length === 1 ? '' : 's'} · ~${pack.tokensUsed} of ${pack.budget} tokens.`,
  );
  if (pack.excludedForStaleness.length > 0) {
    lines.push(`> ${pack.excludedForStaleness.length} document(s) excluded for staleness — see the appendix.`);
  }
  if (pack.omitted.length > 0) {
    lines.push(`> ${pack.omitted.length} document(s) did not fit the budget — see the appendix.`);
  }
  lines.push('');
  lines.push('## Contents');
  lines.push('');
  for (const e of pack.entries) {
    lines.push(`- \`${e.path}\` — ${e.title} (${e.freshness}, relevance ${e.relevance.toFixed(2)})`);
  }
  lines.push('');
  lines.push('---');
  lines.push('');

  for (const e of pack.entries) {
    lines.push(`## ${e.title}`);
    lines.push('');
    lines.push(
      `\`${e.path}\` · freshness: **${e.freshness}** · relevance: ${e.relevance.toFixed(2)} · rank: ${e.rank.toFixed(2)} · ~${e.tokens} tokens${e.truncated ? ' · **truncated to fit budget**' : ''}`,
    );
    lines.push('');
    lines.push(demoteHeadings(e.content.trim()));
    lines.push('');
    if (e.truncated) lines.push(`_[truncated — read \`${e.path}\` for the full text]_`, '');
    lines.push('---');
    lines.push('');
  }

  if (pack.omitted.length > 0 || pack.excludedForStaleness.length > 0) {
    lines.push('## Appendix: what is NOT in this pack');
    lines.push('');
    lines.push('These documents matched the task but were left out. Read them directly if the pack feels thin.');
    lines.push('');
    for (const o of pack.excludedForStaleness) {
      lines.push(`- \`${o.path}\` — excluded: ${o.freshness} (re-run with \`--include-stale\` to include it)`);
    }
    for (const o of pack.omitted) {
      lines.push(`- \`${o.path}\` — ${o.title}: ${o.reason}`);
    }
    lines.push('');
  }

  return lines.join('\n');
}

async function run(argv: string[]): Promise<number> {
  const args = parseArgs(argv, flags);
  if (args.errors.length > 0) {
    for (const e of args.errors) err(c.red(`error: ${e}`));
    return 2;
  }
  if (args.unknown.length > 0) {
    err(c.red(`error: unknown option ${args.unknown.join(', ')}`));
    return 2;
  }

  const task = args.positionals.join(' ').trim();
  if (task === '') {
    err(c.red('error: pack needs a task description'));
    err(c.dim('  e.g. kontext pack "add rate limiting to the ingest API"'));
    return 2;
  }

  const kindsRaw = getList(args, 'kind');
  const bad = kindsRaw.filter((k) => !KINDS.includes(k as DocKind));
  if (bad.length > 0) {
    err(c.red(`error: unknown kind(s) ${bad.join(', ')} — expected one of ${KINDS.join(', ')}`));
    return 2;
  }
  const kinds = kindsRaw as DocKind[];

  const root = findRepoRoot(process.cwd());
  const config = loadConfig(root);
  const budget = getNumber(args, 'budget') ?? config.defaultPackBudget;
  if (budget <= 0) {
    err(c.red('error: --budget must be positive'));
    return 2;
  }

  const docs = await scanDocs(root, config);
  const reports = assessAll(root, docs, config);
  const includeStale = getBool(args, 'include-stale');

  const pack = buildPack(task, reports, {
    budget,
    includeStale,
    ...(kinds.length > 0 ? { kinds } : {}),
  });

  const width = terminalWidth();
  const body = getBool(args, 'json') ? `${JSON.stringify(pack, null, 2)}\n` : `${renderPackMarkdown(pack)}\n`;
  const outPath = getString(args, 'out');

  if (outPath !== undefined) {
    const abs = isAbsolute(outPath) ? outPath : resolve(process.cwd(), outPath);
    mkdirSync(dirname(abs), { recursive: true });
    writeFileSync(abs, body, 'utf8');
    out(abs);
  } else {
    process.stdout.write(body);
  }

  // ---- The loud part. Never let an omission pass unmentioned. ----
  err('');
  errWrap(
    `packed ${pack.entries.length} docs${SEP}~${humanTokens(pack.tokensUsed)}/${humanTokens(pack.budget)} tokens${SEP}task: ${task}`,
    width,
    c.dim,
  );

  const truncated = pack.entries.filter((e) => e.truncated);
  if (truncated.length > 0) {
    err(c.yellow(`  ${truncated.length} doc(s) truncated to fit the budget:`));
    for (const e of truncated) err(c.dim(`    ${truncatePath(e.path, width - 6)}`));
  }

  if (pack.excludedForStaleness.length > 0) {
    err(
      c.yellow(
        `  ${pack.excludedForStaleness.length} doc(s) excluded because they are not trustworthy:`,
      ),
    );
    for (const e of pack.excludedForStaleness) {
      err(c.dim(`    ${markGlyph(e.freshness)} ${truncatePath(e.path, width - 10)} — ${e.freshness}`));
    }
    if (!includeStale) err(c.dim('    (use --include-stale to pack them anyway)'));
  }

  if (pack.omitted.length > 0) {
    err(c.yellow(`  ${pack.omitted.length} doc(s) omitted:`));
    for (const o of pack.omitted) {
      err(c.dim(`    ${truncatePath(o.path, width - 8)} — ${o.reason}`));
    }
    err(c.dim(`    (raise the ceiling with --budget ${budget * 2})`));
  }

  if (pack.entries.length === 0) {
    errWrap('nothing made it into the pack — every candidate was excluded or nothing matched', width, c.red, '  ');
    errWrap('try a broader task string, --include-stale, or a larger --budget', width, c.dim, '  ');
  }
  err('');

  return 0;
}

export const packCommand: CommandDef = {
  name: 'pack',
  summary: 'Assemble a ranked, token-budgeted context bundle for a task.',
  usage: 'kontext pack <task...> [--budget <n>] [--json] [--include-stale] [--kind <k>] [--out <file>]',
  details: [
    'Ranks every doc by lexical relevance to the task, weighted by freshness and kind,',
    'then fills the token budget best-first. The bundle goes to stdout as one clean',
    'markdown document (or JSON with --json) so it can be piped straight into an agent.',
    '',
    'Everything that was left out — truncated, stale-excluded, or over budget — is',
    'reported on stderr. Silent omission is the failure mode this tool exists to kill.',
  ].join('\n'),
  flags,
  run,
};

export default packCommand;
